# Generated by Django 5.0.3 on 2024-03-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spamchan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporter',
            new_name='Report',
        ),
    ]
